### ISSUE TITLE
UI icons unable to magnify

### ISSUE THREAD

**Issue by akoalaman** [MLBAMGames/NHLGames#324]
Hi
I have a graphical UI error which I have had for years-  seems never to be working for me (see attached image). I always set my PC to  150% size increase (HTPC) . This is what is causing this graphical error I beleive. When I reset to 100% it goes away and I see the regular window icons in the top corner. Else its a checkered field (icons missing).

Thanks for a nice program.

<img width="800" alt="nhl" src="https://user-images.githubusercontent.com/92511373/137274844-641ea7e5-247a-4730-b6ea-b3f38a44e72d.png">

**Comment by jwallet** [comment]
we wrote an answer for that issue in our wiki section, it's actually an issue that comes from the UI framework that we use:

(see the last section)
https://github.com/MLBAMGames/NHLGames/wiki/app-not-rendering-well#minimize-fullscreen-close-icons-are-not-displayed--change-the-dpi-settings-in-nhlgamesexe-properties
