### ISSUE TITLE
Server Unavailable

### ISSUE THREAD

**Issue by gallant91** [MLBAMGames/NHLGames#326]
Since updating to the latest version of the app, all streams are displaying as "Server Unavailable" - have tried adding application as an exception to Windows Defender rules in case this new version was being flagged, but this had no change. Have tried in both simplified and complete download versions and both produce same results

**Comment by fsjja1** [comment]
Same issue here.

**Comment by d-kar** [comment]
I usually go reddit for possible solutions first.
https://www.reddit.com/r/nhl_games/comments/qigxno/freegamezga_offline_please_switch_to

**Comment by JellOwned** [comment]
In the app's settings, try to change the **Server's Hostname** to freesports.ddns.net and reopen it. It worked for me.

**Comment by takla21** [comment]
@JellOwned solution works for me too.

**Comment by whoseon2nd** [comment]
streamer opens then closes 20 secs
mpv path set \
proxy set
hosts set to 2
still no faceoff

**Comment by romdj** [comment]
+1 for @JellOwned solution

**Comment by kavemang** [comment]
This worked for me sort of, it got rid of the server unavailable message, but all streams have a yellow exclamation saying "broken stream"
