### ISSUE TITLE
Server unavailable

### ISSUE THREAD

**Issue by Gohu1608** [MLBAMGames/NHLGames#329]
Doesn't work until I downlad the latest version 1.6.3.1
![NHL_probleme](https://user-images.githubusercontent.com/93746133/140436174-50381d8f-122f-4db2-87fb-4fcbabcf78a6.png)

**Comment by cfpatchett** [comment]
Seems like this was a server-side issue, as my favorite streaming website also lost it's streams for a bit there. Everything looks like it's back to normal now.

**Comment by Habsfan1962** [comment]
I tried changing Hostname to freesport.ddns.net and still did not work. I removed app from pc. I removed all older versions. I upgraded to version 1.6.3.1 it still kept saying "server unavailable". I checked the status link which said everything was working fine. I even messed around with the host file, the proxy port etc. still nothing. I was ready to give up then wondered if the site was being blocked by my ISP ? Turned on my VPN and Bingo !  It works with the VPN turned on. go figure.

**Comment by cfpatchett** [comment]
Seems like the issues from the past couple nights are caused by something separate. The fix I originally posted worked for a couple days, but 2 nights ago I was unable to watch anything, so I'm assuming there's something else messing with the streams.
