### ISSUE TITLE
Available feeds went black, new feeds unavailable

### ISSUE THREAD

**Issue by natalieS21** [MLBAMGames/NHLGames#330]
Anyone else having issues?

**Comment by DarkAng31** [comment]
Yes, I have had this happen several times mid-stream over the last couple of weeks.  I will be watching the game live and the stream will freeze for several minutes until i finally close the stream and attempt to re-open, but the stream just opens to a black window.

I have checked my Pi-hole to verify it was not blocking anything and it was not, but I did change my DNS on this device anyway as a test but get the same results.

I have been unable to find a solution for this when it happens.
