### ISSUE TITLE
Game stream not found or unavailable on the server for streams older then 1 day

### ISSUE THREAD

**Issue by d-kar** [MLBAMGames/NHLGames#332]
Can't watch older streams now, shows yellow triangles with 'Broken stream' message. Is this a known issue? Couldn't find any information on Wiki.
I remeber reading something about it that program had to guess link location? Is this not working anymore?
Any workaround?

**Comment by untoor** [comment]
@d-kar Nowadays streams are working, i assume you know it? You need to change server's hostname to **freesports** to get links appear. **freegamez** -server is broken.

**Comment by d-kar** [comment]
> @d-kar Nowadays streams are working, i assume you know it? You need to change server's hostname to **freesports** to get links appear. **freegamez** -server is broken.

I'm not talking about live games or that were playes 1 day ago, that works fine. Older games do not work, showing broken streams.
![image](https://user-images.githubusercontent.com/10633128/147885672-f2978d8e-3bd5-43d2-9817-123a90737a64.png)

**Comment by untoor** [comment]
> > @d-kar Nowadays streams are working, i assume you know it? You need to change server's hostname to **freesports** to get links appear. **freegamez** -server is broken.
> 
> I'm not talking about live games or that were playes 1 day ago, that works fine. Older games do not work, showing broken streams. ![image](https://user-images.githubusercontent.com/10633128/147885672-f2978d8e-3bd5-43d2-9817-123a90737a64.png)

Ok. Those Recaps works but i know, they're only recaps.
After posting my previous comment i saw that todays streams were broken, but watching now via browser from different provider i'm able to see matches.

**Comment by murko69** [comment]
> > @d-kar Nowadays streams are working, i assume you know it? You need to change server's hostname to **freesports** to get links appear. **freegamez** -server is broken.
> 
> I'm not talking about live games or that were playes 1 day ago, that works fine. Older games do not work, showing broken streams. ![image](https://user-images.githubusercontent.com/10633128/147885672-f2978d8e-3bd5-43d2-9817-123a90737a64.png)

AFAIK this has always been the case, at least the past +year I've been using this app, so I thought this was 'normal behaviour' due to limitations in storage or something.

**Comment by d-kar** [comment]
> > > @d-kar Nowadays streams are working, i assume you know it? You need to change server's hostname to **freesports** to get links appear. **freegamez** -server is broken.
> > 
> > 
> > I'm not talking about live games or that were playes 1 day ago, that works fine. Older games do not work, showing broken streams.
> 
> AFAIK this has always been the case, at least the past +year I've been using this app, so I thought this was 'normal behaviour' due to limitations in storage or something.

Well it should be possible to get older games, since they are available through NHL Live if you connect with account. They are just on different servers than live games and there's a different way of getting those streams.
