### ISSUE TITLE
Getting "Broken stream" in Day-Of Schedule

### ISSUE THREAD

**Issue by jigratz** [MLBAMGames/NHLGames#339]
Hello- First of, thank you to everyone who contributed to this project. It's absolutely fantastic! 

Since yesterday, I've been receiving a broken streams for all games:

![NHL Game Broken Stream Screenshot](https://user-images.githubusercontent.com/81345856/155447779-d481693e-5ef7-4031-a11e-9f344c0f5ebc.PNG)

I tried both Server's Hostnames and Alternate Content Delivery Network both on and off.

I would certainly appreciate any help you could provide!

Thank you,
-Joe Gratz (a fan)

**Comment by OatmealParmesan** [comment]
+1 same issue, and did the same troubleshooting.

**Comment by AwesomeAL** [comment]
Same issues problems with both servers:

```
[11:32:16] Status: Server freegamez.ga seems down

[11:32:25] Status: Setting updated for 'Server's Hostname' to 'freesports.ddns.net'

[11:32:25] Fetching: Game schedule for 2022-02-26 from NHL.tv

[11:32:25] Status: Server freesports.ddns.net seems down
```

![NHLGames](https://user-images.githubusercontent.com/42872637/155700786-8fbc18fa-b2a5-490b-a581-23d9d95f7ef5.png)

**Comment by evol1945** [comment]
постоянно пишет Server unavailable. Что делать?





































































![image](https://user-images.githubusercontent.com/101119967/157052487-8fb5ed2c-f1ab-4050-a166-db6ba96b8f50.png)




.

**Comment by zijlmark** [comment]
I'm getting the same issue
![image](https://user-images.githubusercontent.com/44618325/164124021-42c3a9c0-376d-45f5-b743-73540a5564fd.png)
