### ISSUE TITLE
Only getting "No Stream Available" on all games

### ISSUE THREAD

**Issue by natalieS21** [MLBAMGames/NHLGames#342]
Just installed this great app on a new Win 11 machine.  But all I keep getting is "No Stream Available" on all games listed (it is listing the games).  Have tried stuff that worked to fix things in the past and no changes.  Is this not working any longer?  I hope it is, it was fantastic.

**Comment by marketingmike** [comment]
I believe this was addressed on Reddit but nhl.tv is not broadcasting the games.

**Comment by MattMailloux** [comment]
I am experiencing the same thing.
